# Generated by Django 3.1.4 on 2020-12-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historicos', '0002_remove_historicos_conclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicos',
            name='remedios',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
