# Generated by Django 3.1.4 on 2020-12-30 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_agendamentos_cancelado'),
        ('historicos', '0003_historicos_remedios'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicos',
            name='conclusao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='agendamentos.agendamentos'),
            preserve_default=False,
        ),
    ]
