# Generated by Django 3.1.4 on 2020-12-30 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_agendamentos_cancelado'),
        ('historicos', '0004_historicos_conclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicos',
            name='id_agendamento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='agendamentos.agendamentos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicos',
            name='conclusao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
