# Generated by Django 3.1.4 on 2021-01-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historicos', '0005_auto_20201230_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicos',
            options={'managed': True, 'verbose_name': 'historico', 'verbose_name_plural': 'historicos'},
        ),
    ]
