# Generated by Django 3.1.4 on 2020-12-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
