# Generated by Django 3.1.4 on 2021-01-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_agendamentos_cancelado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamentos',
            options={'managed': True, 'verbose_name': 'agendamento', 'verbose_name_plural': 'agendamentos'},
        ),
    ]
