# Generated by Django 3.1.4 on 2021-01-06 20:16

from django.db import migrations, models
import django.db.models.deletion
import imagens.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historicos', '0005_auto_20201230_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagensHistorico',
            fields=[
                ('id_imagem_historico', models.AutoField(primary_key=True, serialize=False)),
                ('imagens', models.ImageField(blank=True, null=True, upload_to=imagens.models.imagens_historicos)),
                ('id_historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='historicos.historicos')),
            ],
        ),
    ]
